"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
import styles from "./account.module.css";
import { MemoryPanel, type MemoryData } from "./MemoryPanel";

export interface MeData { account?: { email?: string | null; emailVerifiedAt?: string | null; createdAt?: string }; profile: { displayName?: string | null; locale: string; explanationDepth: string; memoryEnabled: boolean } }
export interface LibraryData { favorites: Array<{ entityId: string; entityType: string; title: string; slug: string }>; readingProgress: Array<{ entityId: string; entityType: string; title: string; slug: string; progress: number }>; journeyProgress: Array<{ journeyId: string; title: string; slug: string; nodeOrdinal: number; completedAt?: string | null }> }
export interface SessionData { id: string; current: boolean; createdAt: string; lastSeenAt: string; expiresAt: string }
const emptyLibrary: LibraryData = { favorites: [], readingProgress: [], journeyProgress: [] };
function entityHref(item: { entityType: string; slug: string }) { return item.entityType === "person" ? `/thinker/${item.slug}` : `/${item.entityType}/${item.slug}`; }

export function AccountDashboard({ initialMe, initialLibrary = emptyLibrary, initialSessions = [], initialMemories = [] }: { initialMe: MeData; initialLibrary?: LibraryData; initialSessions?: SessionData[]; initialMemories?: MemoryData[] }) {
  const router = useRouter(); const [me, setMe] = useState<MeData>(initialMe); const [library, setLibrary] = useState<LibraryData>(initialLibrary); const [sessions, setSessions] = useState<SessionData[]>(initialSessions); const [error, setError] = useState<string>(); const [pending, setPending] = useState(false);
  async function load() { try { const [meResponse, libraryResponse, sessionResponse] = await Promise.all([fetch("/api/v1/me"), fetch("/api/v1/me/library"), fetch("/api/v1/auth/sessions")]); if ([meResponse, libraryResponse, sessionResponse].some((response) => response.status === 401)) { router.replace("/account/login"); return; } const [mePayload, libraryPayload, sessionPayload] = await Promise.all([meResponse.json(), libraryResponse.json(), sessionResponse.json()]) as [{ data: MeData }, { data: LibraryData }, { data: SessionData[] }]; setMe(mePayload.data); setLibrary(libraryPayload.data); setSessions(sessionPayload.data); } catch { setError("无法读取账户数据。"); } }
  async function saveProfile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(undefined); const form = new FormData(event.currentTarget); try { const response = await fetch("/api/v1/me", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ displayName: form.get("displayName") || null, locale: form.get("locale"), explanationDepth: form.get("explanationDepth"), memoryEnabled: form.get("memoryEnabled") === "on" }) }); if (!response.ok) throw new Error("保存设置失败。"); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "保存设置失败。"); } finally { setPending(false); } }
  async function logout() { await fetch("/api/v1/auth/logout", { method: "POST" }); router.replace("/"); router.refresh(); }
  async function revoke(id: string) { const response = await fetch(`/api/v1/auth/sessions/${id}`, { method: "DELETE" }); if (response.ok) { const current = sessions.find((item) => item.id === id)?.current; if (current) { router.replace("/account/login"); router.refresh(); } else await load(); } }
  async function exportData() { const response = await fetch("/api/v1/me/export", { method: "POST" }); if (!response.ok) { setError("数据导出失败。"); return; } const blob = await response.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "atlas-account-export.json"; anchor.click(); URL.revokeObjectURL(url); }
  async function deleteAccount() { const confirmation = window.prompt("此操作会永久删除账户、对话、收藏、进度和记忆。请输入 DELETE MY ACCOUNT："); if (confirmation !== "DELETE MY ACCOUNT") return; const response = await fetch("/api/v1/me/account", { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ confirmation }) }); if (response.ok) { router.replace("/"); router.refresh(); } else setError("账户删除失败。"); }
  return <div className={styles.dashboard}><section className={styles.hero}><span className={styles.eyebrow}>MY ATLAS</span><h1>{me.profile.displayName || "我的思想星图"}</h1><p>{me.account?.email} · 收藏、阅读进度、旅程与对话都只对当前账户可见。</p></section>
    {error && <p className={styles.error} role="alert">{error}</p>}
    <section className={styles.panel}><h2>个人设置</h2><form className={styles.form} onSubmit={saveProfile}><label>显示名称<input defaultValue={me.profile.displayName ?? ""} name="displayName" /></label><label>语言<select defaultValue={me.profile.locale} name="locale"><option value="zh-CN">简体中文</option><option value="en-US">English</option></select></label><label>解释深度<select defaultValue={me.profile.explanationDepth} name="explanationDepth"><option value="concise">简洁</option><option value="balanced">平衡</option><option value="deep">深入</option></select></label><label><span><input defaultChecked={me.profile.memoryEnabled} name="memoryEnabled" type="checkbox" /> 启用显式长期记忆</span></label><button disabled={pending}>保存设置</button></form></section>
    <div className={styles.columns}><section className={styles.panel}><h2>收藏</h2>{library.favorites.length ? <ul>{library.favorites.map((item) => <li key={item.entityId}><Link href={entityHref(item)}>{item.title}</Link><span>{item.entityType}</span></li>)}</ul> : <p>还没有收藏。</p>}</section><section className={styles.panel}><h2>阅读进度</h2>{library.readingProgress.length ? <ul>{library.readingProgress.map((item) => <li key={item.entityId}><Link href={entityHref(item)}>{item.title}</Link><span>{Math.round(item.progress * 100)}%</span></li>)}</ul> : <p>还没有同步阅读进度。</p>}</section></div>
    <section className={styles.panel}><h2>思想旅程</h2>{library.journeyProgress.length ? <ul>{library.journeyProgress.map((item) => <li key={item.journeyId}><Link href={`/journey/${item.slug}`}>{item.title}</Link><span>{item.completedAt ? "已完成" : `第 ${item.nodeOrdinal + 1} 站`}</span></li>)}</ul> : <p>还没有同步旅程进度。</p>}</section>
    <MemoryPanel enabled={me.profile.memoryEnabled} initialMemories={initialMemories} />
    <section className={styles.panel}><h2>设备会话</h2><ul>{sessions.map((session) => <li key={session.id}><span>{session.current ? "当前设备" : `登录于 ${new Date(session.createdAt).toLocaleString("zh-CN")}`}</span><button onClick={() => revoke(session.id)} type="button">{session.current ? "退出当前设备" : "远程注销"}</button></li>)}</ul></section>
    <section className={styles.panel}><h2>数据与隐私</h2><div className={styles.links}><button onClick={exportData} type="button">导出我的数据</button><button onClick={logout} type="button">退出登录</button></div></section>
    <section className={`${styles.panel} ${styles.danger}`}><h2>永久删除账户</h2><p>将硬删除消息、记忆、收藏、进度与会话，无法撤销。</p><button onClick={deleteAccount} type="button">删除账户及全部数据</button></section>
  </div>;
}
